name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  hadolinting:
    name: Linting docker image fule
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf
      with:
        output-file: results.txt
    - uses: actions/upload-artifact@v4
      with:
        path: results.txt
        name: Linting Results
        
  build:
    name: Building Docker Images
    runs-on: ubuntu-latest
    needs: hadolinting
    steps:
    - uses: actions/checkout@v4
    - name: logging in
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ vars.DOCKER_USERNAME }} --password-stdin 
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ vars.DOCKER_USERNAME }}/todo_list:latest --push
        
    - name: logout
      run: |
        docker logout
